### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by DavidYT** [mrlolethan/mrlolethan.com#1]
COMMANDS:
- /koth loot
- /koth hour

NEW STUFF:
- Chest Loot [for one who caps]
- Scheduled koths [example: Dragon koth: 16:00h, etc...)

**Comment by EthanJoyce** [comment]
Please open an issue for each idea, and be more elaborate.

**Comment by EthanJoyce** [comment]
Also, you opened this on the wrong repo. I believe you meant to open it here: https://github.com/mrlolethan/nexgen-koths

**Comment by DavidYT** [comment]
sorry
